apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9093"
  name: alertmanager
  namespace: {{.NameSpace}}
  labels:
    app: dt-alertmanager
spec:
  ports:
  - port: 9093
    targetPort: 9093
    name: tcp
  selector:
    app: dt-alertmanager
