apiVersion: v1
kind: Service
metadata:
  name: dtalert
  namespace: {{.NameSpace}}
  labels:
    app: dt-alert
spec:
  ports:
  - port: 8085
    targetPort: 8085
    name: tcp
  selector:
    app: dt-alert
