apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: loki-grafana
  namespace: {{.NameSpace}}
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: loki-grafana
          servicePort: 3000
