apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{.NameSpace}}
  labels:
    app: dtmysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: tcp
  selector:
    app: dtmysql
