apiVersion: v1
kind: Service
metadata:
  name: matrix
  namespace: {{.NameSpace}}
  labels:
    app: matrix
spec:
  ports:
  - port: 8864
    targetPort: 8864
    nodePort: {{.MatrixPort}}
    name: tcp
  type: NodePort
  selector:
    app: matrix
