apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9091"
  name: pushgateway
  namespace: {{.NameSpace}}
  labels:
    app: dt-pushgateway
spec:
  ports:
  - port: 9091
    targetPort: 9091
    name: tcp
  selector:
    app: dt-pushgateway
