package kube

type T1 DeployClusterImageStoreSchema
type T2 ClusterK8sAvailable
type T3 ClusterInfo
type T4 DeployClusterProductRelSchema
type T5 DeployNamespaceClientSchema
type T6 DeployNamespaceListSchema
type T7 DeployProductListSchema
type T8 ImportInitMoudleSchema
type T9 DeployNamespaceEventSchema
type T10 WorloadStepSchema
type T11 WorkloaPartSchema
type T12 WorkloadDefinitionSchema
