apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: em-prometheus-role
  namespace: {{.NameSpace}}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: em-prometheus-sa
  namespace: {{.NameSpace}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: em-prometheus-rolebinding
  namespace: {{.NameSpace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: em-prometheus-role
subjects:
  - kind: ServiceAccount
    name: em-prometheus-sa
    namespace: {{.NameSpace}}

