CREATE TABLE IF NOT EXISTS `workload_definition` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `version` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `params` text COLLATE utf8mb4_unicode_ci,
  `latest` int(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

BEGIN;
INSERT INTO `workload_definition` VALUES (1, 'zookeeper', 'v1', '[{\"key\":\"Image\",\"ref\":\"spec.workloadpatrs.0.steps.1.object.image\"},{\"key\":\"Replica\",\"ref\":\"spec.workloadpatrs.0.baseworkload.parameters.spec.replicas\"},{\"key\":\"ResourceRequest.cpu\",\"ref\":\"spec.workloadpatrs.0.steps.1.object.resources.requests.cpu\"},{\"key\":\"ResourceRequest.memory\",\"ref\":\"spec.workloadpatrs.0.steps.1.object.resources.requests.memory\"},{\"key\":\"ResourceLimit.cpu\",\"ref\":\"spec.workloadpatrs.0.steps.1.object.resources.limits.cpu\"},{\"key\":\"ResourceLimit.memory\",\"ref\":\"spec.workloadpatrs.0.steps.1.object.resources.limits.memory\"},{\"key\":\"Ports.0\",\"ref\":\"spec.workloadpatrs.0.steps.3.object.spec.ports.0.port\"},{\"key\":\"Environment.ZK_SERVERS\",\"ref\":\"spec.workloadpatrs.0.steps.1.object.env.0.value\"},{\"key\":\"Environment.ZOO_INIT_LIMIT\",\"ref\":\"spec.workloadpatrs.0.steps.1.object.env.1.value\"},{\"key\":\"Environment.ZOO_MAX_CLIENT_CNXNS\",\"ref\":\"spec.workloadpatrs.0.steps.1.object.env.2.value\"},{\"key\":\"StorageClass\",\"ref\":\"spec.workloadpatrs.0.steps.0.object.spec.storageClassName\"}]', 1);
INSERT INTO `workload_definition` VALUES (2, 'redis', 'v1', '[{\"key\":\"Image\",\"ref\":\"spec.workloadpatrs.0.steps.3.object.image\"},{\"key\":\"Replica\",\"ref\":\"spec.workloadpatrs.0.baseworkload.parameters.spec.replicas\"},{\"key\":\"ResourceRequest.cpu\",\"ref\":\"spec.workloadpatrs.0.steps.3.object.resources.requests.cpu\"},{\"key\":\"ResourceRequest.memory\",\"ref\":\"spec.workloadpatrs.0.steps.3.object.resources.requests.memory\"},{\"key\":\"ResourceLimit.cpu\",\"ref\":\"spec.workloadpatrs.0.steps.3.object.resources.limits.cpu\"},{\"key\":\"ResourceLimit.memory\",\"ref\":\"spec.workloadpatrs.0.steps.3.object.resources.limits.memory\"},{\"key\":\"Ports.0\",\"ref\":\"spec.workloadpatrs.0.steps.5.object.spec.ports.0.port\"},{\"key\":\"ConfigPaths\",\"ref\":\"spec.workloadpatrs.0.steps.0.object.data\"}]', 1);
INSERT INTO `workload_definition` VALUES (3, 'mysql', 'v1', '[{\"key\":\"Image\",\"ref\":\"spec.workloadpatrs.0.steps.6.object.image\"},{\"key\":\"Image\",\"ref\":\"spec.workloadpatrs.0.steps.4.object.image\"},{\"key\":\"Replica\",\"ref\":\"spec.workloadpatrs.0.baseworkload.parameters.spec.replicas\"},{\"key\":\"ResourceRequest.cpu\",\"ref\":\"spec.workloadpatrs.0.steps.6.object.resources.requests.cpu\"},{\"key\":\"ResourceRequest.memory\",\"ref\":\"spec.workloadpatrs.0.steps.6.object.resources.requests.memory\"},{\"key\":\"ResourceLimit.cpu\",\"ref\":\"spec.workloadpatrs.0.steps.6.object.resources.limits.cpu\"},{\"key\":\"ResourceLimit.memory\",\"ref\":\"spec.workloadpatrs.0.steps.6.object.resources.limits.memory\"},{\"key\":\"Ports.0\",\"ref\":\"spec.workloadpatrs.0.steps.7.object.spec.ports.0.port\"},{\"key\":\"Environment.MYSQL_ALLOW_EMPTY_PASSWORD\",\"ref\":\"spec.workloadpatrs.0.steps.6.object.env.0.value\"},{\"key\":\"ConfigPaths\",\"ref\":\"spec.workloadpatrs.0.steps.1.object.data\"},{\"key\":\"StorageClass\",\"ref\":\"spec.workloadpatrs.0.steps.0.object.spec.storageClassName\"}]', 1);
INSERT INTO `workload_definition` VALUES (4, 'pushgateway', 'v1', '[{\"key\":\"Image\",\"ref\":\"spec.workloadpatrs.0.steps.1.object.image\"},{\"key\":\"Replica\",\"ref\":\"spec.workloadpatrs.0.baseworkload.parameters.spec.replicas\"},{\"key\":\"ResourceRequest.cpu\",\"ref\":\"spec.workloadpatrs.0.steps.1.object.resources.requests.cpu\"},{\"key\":\"ResourceRequest.memory\",\"ref\":\"spec.workloadpatrs.0.steps.1.object.resources.requests.memory\"},{\"key\":\"ResourceLimit.cpu\",\"ref\":\"spec.workloadpatrs.0.steps.1.object.resources.limits.cpu\"},{\"key\":\"ResourceLimit.memory\",\"ref\":\"spec.workloadpatrs.0.steps.1.object.resources.limits.memory\"},{\"key\":\"Ports.0\",\"ref\":\"spec.workloadpatrs.0.steps.2.object.spec.ports.0.port\"}]', 1);
INSERT INTO `workload_definition` VALUES (5, 'prometheus', 'v1', '[{\"key\":\"Image\",\"ref\":\"spec.workloadpatrs.0.steps.4.object.image\"},{\"key\":\"Replica\",\"ref\":\"spec.workloadpatrs.0.baseworkload.parameters.spec.replicas\"},{\"key\":\"ResourceRequest.cpu\",\"ref\":\"spec.workloadpatrs.0.steps.4.object.resources.requests.cpu\"},{\"key\":\"ResourceRequest.memory\",\"ref\":\"spec.workloadpatrs.0.steps.4.object.resources.requests.memory\"},{\"key\":\"ResourceLimit.cpu\",\"ref\":\"spec.workloadpatrs.0.steps.4.object.resources.limits.cpu\"},{\"key\":\"ResourceLimit.memory\",\"ref\":\"spec.workloadpatrs.0.steps.4.object.resources.limits.memory\"},{\"key\":\"Ports.0\",\"ref\":\"spec.workloadpatrs.0.steps.5.object.spec.ports.0.port\"},{\"key\":\"ConfigPaths\",\"ref\":\"spec.workloadpatrs.0.steps.1.object.data\"},{\"key\":\"StorageClass\",\"ref\":\"spec.workloadpatrs.0.steps.0.object.spec.storageClassName\"}]', 1);
INSERT INTO `workload_definition` VALUES (6, 'kafka', 'v1', '[{\"key\":\"Image\",\"ref\":\"spec.workloadpatrs.0.steps.0.object.image\"},{\"key\":\"Replica\",\"ref\":\"spec.workloadpatrs.0.baseworkload.parameters.spec.replicas\"},{\"key\":\"ResourceRequest.cpu\",\"ref\":\"spec.workloadpatrs.0.steps.0.object.resources.requests.cpu\"},{\"key\":\"ResourceRequest.memory\",\"ref\":\"spec.workloadpatrs.0.steps.0.object.resources.requests.memory\"},{\"key\":\"ResourceLimit.cpu\",\"ref\":\"spec.workloadpatrs.0.steps.0.object.resources.limits.cpu\"},{\"key\":\"ResourceLimit.memory\",\"ref\":\"spec.workloadpatrs.0.steps.0.object.resources.limits.memory\"},{\"key\":\"Ports.0\",\"ref\":\"spec.workloadpatrs.0.steps.1.object.spec.ports.0.port\"},{\"key\":\"Environment.KAFKA_HEAP_OPTS\",\"ref\":\"spec.workloadpatrs.0.steps.0.object.env.0.value\"},{\"key\":\"Environment.KAFKA_OPTS\",\"ref\":\"spec.workloadpatrs.0.steps.0.object.env.1.value\"}]', 1);
COMMIT;

CREATE TABLE IF NOT EXISTS `workload_part` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `parameters` text COLLATE utf8mb4_unicode_ci,
  `workload_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

BEGIN;
INSERT INTO `workload_part` VALUES (1, 'leader', 'statefulset', '{\"spec\":{\"replicas\":3,\"serviceName\":\"@zk-hs\"}}', 1);
INSERT INTO `workload_part` VALUES (2, 'singlenode', 'deployment', '{\"spec\":{\"replicas\":1}}', 2);
INSERT INTO `workload_part` VALUES (3, 'master-slave', 'statefulset', '{\"spec\":{\"replicas\":2,\"serviceName\":\"@mysql-svc\"}}', 3);
INSERT INTO `workload_part` VALUES (4, 'singlenode', 'deployment', '{\"spec\":{\"replicas\":1}}', 4);
INSERT INTO `workload_part` VALUES (5, 'master', 'statefulset', '{\"spec\":{\"replicas\":1,\"serviceName\":\"@prometheus-svc\"}}', 5);
INSERT INTO `workload_part` VALUES (6, 'master', 'statefulset', '{\"spec\":{\"replicas\":2,\"serviceName\":\"@kafka-svc\"}}', 6);
COMMIT;

CREATE TABLE IF NOT EXISTS `workload_step` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `action` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `object` text COLLATE utf8mb4_unicode_ci,
  `workloadpart_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

BEGIN;
INSERT INTO `workload_step` VALUES (1, 'zkdata', 'pvc', 'bound', '{\"spec\":{\"storageClassName\":\"local-storage-workload-zk\",\"accessModes\":[\"ReadWriteOnce\"],\"resources\":{\"requests\":{\"storage\":\"5G\"}}}}', 1);
INSERT INTO `workload_step` VALUES (2, 'zk-sts', 'container', 'bound', '{\"image\":\"zookeeper:3.4.14_02\",\"env\":[{\"name\":\"ZK_SERVERS\",\"value\":\"3\"},{\"name\":\"ZOO_INIT_LIMIT\",\"value\":\"10\"},{\"name\":\"ZOO_MAX_CLIENT_CNXNS\",\"value\":\"200\"},{\"name\":\"SERVER_JVMFLAGS\",\"value\":\"-javaagent:./dtstack/prometheus/jmx_prometheus_javaagent-0.14.0.jar=9505:./dtstack/prometheus/zookeeper.yml\"}],\"resources\":{\"requests\":{\"memory\":\"1Gi\",\"cpu\":\"1\"},\"limits\":{\"memory\":\"3Gi\",\"cpu\":\"3\"}},\"ports\":[{\"containerPort\":2888,\"name\":\"server\"},{\"containerPort\":2181,\"name\":\"client\"},{\"containerPort\":3888,\"name\":\"leader-election\"},{\"containerPort\":9505,\"name\":\"jmx-prom-agent\"}],\"command\":[\"sh\",\"-c\",\"/zookeeper/bin/dtstack/start-zookeeper-k8s.sh\"],\"readinessProbe\":{\"exec\":{\"command\":[\"/zookeeper/bin/dtstack/zookeeper-healthcheck.sh\",\"2181\"]},\"initialDelaySeconds\":10,\"timeoutSeconds\":5},\"livenessProbe\":{\"exec\":{\"command\":[\"/zookeeper/bin/dtstack/zookeeper-healthcheck.sh\",\"2181\"]},\"initialDelaySeconds\":10,\"timeoutSeconds\":5},\"volumeMounts\":[{\"name\":\"zkdata\",\"mountPath\":\"/data\",\"subPath\":\"zk_data\"},{\"name\":\"zkdata\",\"mountPath\":\"/datalog\",\"subPath\":\"zk_datalog\"},{\"name\":\"zkdata\",\"mountPath\":\"/logs\",\"subPath\":\"zk_logs\"}],\"securityContext\":{\"runAsUser\":0,\"runAsGroup\":0}}', 1);
INSERT INTO `workload_step` VALUES (3, 'zk-hs', 'service', 'createorupdate', '{\"spec\":{\"ports\":[{\"port\":2888,\"name\":\"server\"},{\"port\":3888,\"name\":\"leader-election\"},{\"port\":9505,\"name\":\"jmx-prom-agent\"}],\"clusterIP\":\"None\",\"selector\":{\"app\":\"@leader\"}}}', 1);
INSERT INTO `workload_step` VALUES (4, 'zk-cs', 'service', 'createorupdate', '{\"spec\":{\"ports\":[{\"port\":2181,\"name\":\"client\",\"targetPort\":2181}],\"selector\":{\"app\":\"@leader\"}}}', 1);
INSERT INTO `workload_step` VALUES (5, 'redis-cm', 'conf', 'createorupdate', '{\"data\":{\"redis.conf\":\"bind 127.0.0.1\\nport 6379\\ntcp-backlog 511\\ntimeout 0\\ntcp-keepalive 300\\ndaemonize no\\nsupervised no\\npidfile /var/run/redis_6379.pid\\nloglevel notice\\nlogfile \\\"\\\"\\ndatabases 16\\nsave 900 1\\nsave 300 10\\nsave 60 10000\\nstop-writes-on-bgsave-error yes\\nrdbcompression yes\\nrdbchecksum yes\\ndbfilename dump.rdb\\ndir ./\\nslave-serve-stale-data yes\\nslave-read-only yes\\nrepl-diskless-sync no\\nrepl-diskless-sync-delay 5\\nrepl-disable-tcp-nodelay no\\nslave-priority 100\\nappendonly no\\nappendfilename \\\"appendonly.aof\\\"\\nappendfsync everysec\\nno-appendfsync-on-rewrite no\\nauto-aof-rewrite-percentage 100\\nauto-aof-rewrite-min-size 64mb\\naof-load-truncated yes\\nlua-time-limit 5000\\nslowlog-log-slower-than 10000\\nslowlog-max-len 128\\nlatency-monitor-threshold 0\\nnotify-keyspace-events \\\"\\\"\\nhash-max-ziplist-entries 512\\nhash-max-ziplist-value 64\\nlist-max-ziplist-size -2\\nlist-compress-depth 0\\nzset-max-ziplist-entries 128\\nzset-max-ziplist-value 64\\nhll-sparse-max-bytes 3000\\nactiverehashing yes\\nclient-output-buffer-limit normal 0 0 0\\nclient-output-buffer-limit slave 256mb 64mb 60\\nclient-output-buffer-limit pubsub 32mb 8mb 60\\nhz 10\\naof-rewrite-incremental-fsync yes\\nrename-command FLUSHALL \\\"\\\"\\nrename-command FLUSHDB  \\\"\\\"\\nrename-command SHUTDOWN \\\"\\\"\\n\"}}', 2);
INSERT INTO `workload_step` VALUES (6, 'redisconfig-volume', 'volume', 'bound', '{\"configMap\":{\"name\":\"@redis-cm\"}}', 2);
INSERT INTO `workload_step` VALUES (7, 'redis-localtime', 'volume', 'bound', '{\"hostPath\":{\"path\":\"/etc/localtime\"}}', 2);
INSERT INTO `workload_step` VALUES (8, 'redis-dp', 'container', 'bound', '{\"image\":\"redis:3.2.12_02\",\"imagePullPolicy\":\"Always\",\"resources\":{\"requests\":{\"memory\":\"1Gi\",\"cpu\":\"1\"},\"limits\":{\"memory\":\"3Gi\",\"cpu\":\"3\"}},\"ports\":[{\"containerPort\":6379}],\"livenessProbe\":{\"exec\":{\"command\":[\"/usr/bin/dtstack/redis-liveness.sh\"]},\"initialDelaySeconds\":30,\"periodSeconds\":10,\"timeoutSeconds\":5},\"readinessProbe\":{\"exec\":{\"command\":[\"/usr/bin/dtstack/redis-readiness.sh\"]},\"initialDelaySeconds\":5,\"periodSeconds\":2,\"timeoutSeconds\":1},\"volumeMounts\":[{\"name\":\"redisconfig-volume\",\"mountPath\":\"/usr/local/etc/redis\"}]}', 2);
INSERT INTO `workload_step` VALUES (9, 'redis-exporter', 'container', 'bound', '{\"image\":\"redis_exporter:v1.14.0_01\",\"resources\":{\"requests\":{\"cpu\":\"100m\",\"memory\":\"100Mi\"}},\"ports\":[{\"containerPort\":9121}],\"volumeMounts\":[{\"name\":\"redis-localtime\",\"mountPath\":\"/etc/localtime\"}]}', 2);
INSERT INTO `workload_step` VALUES (10, 'redis-svc', 'service', 'createorupdate', '{\"metadata\":{\"annotations\":{\"prometheus.io/scrape\":\"true\",\"prometheus.io/port\":\"9121\"}},\"spec\":{\"ports\":[{\"name\":\"redis\",\"port\":6379,\"targetPort\":6379},{\"name\":\"prom\",\"port\":9121,\"targetPort\":9121}],\"selector\":{\"app\":\"@singlenode\"}}}', 2);
INSERT INTO `workload_step` VALUES (11, 'mysql-data', 'pvc', 'bound', '{\"spec\":{\"storageClassName\":\"local-storage-workload-mysql\",\"accessModes\":[\"ReadWriteOnce\"],\"resources\":{\"requests\":{\"storage\":\"5Gi\"}}}}', 3);
INSERT INTO `workload_step` VALUES (12, 'mysqlcm', 'conf', 'createorupdate', '{\"primary.cnf\":\"\\n# Apply this config only on the primary.\\n[mysqld]\\nlog-bin\\n\\n\",\"replica.cnf\":\"\\n# Apply this config only on replicas.\\n[mysqld]\\nsuper-read-only\\n\",\"hive.sql\":\"\\n# init hive sql.\\n\",\"createuser.sh\":\"\\n# create mysql user script.\\n\"}', 3);
INSERT INTO `workload_step` VALUES (13, 'mysql-conf', 'volume', 'bound', '{\"emptyDir\":{}}', 3);
INSERT INTO `workload_step` VALUES (14, 'mysql-cmvolume', 'volume', 'bound', '{\"configMap\":{\"name\":\"@mysqlcm\"}}', 3);
INSERT INTO `workload_step` VALUES (15, 'init-mysql', 'init-container', 'bound', '{\"image\":\"mysql:5.7.32_02\",\"imagePullPolicy\":\"Always\",\"env\":[{\"name\":\"MYSQL_ALLOW_EMPTY_PASSWORD\",\"value\":\"1\"}],\"command\":[\"bash\",\"-c\",\"/usr/bin/dtstack/init-mysql.sh\"],\"volumeMounts\":[{\"name\":\"mysql-conf\",\"mountPath\":\"/mnt/conf.d\"},{\"name\":\"mysql-cmvolume\",\"mountPath\":\"/mnt/config-map\"},{\"name\":\"mysql-data\",\"mountPath\":\"/var/lib/mysql\",\"subPath\":\"mysql\"}]}', 3);
INSERT INTO `workload_step` VALUES (16, 'clone-mysql', 'init-container', 'bound', '{\"image\":\"xtrabackup:2.4.21_02\",\"env\":[{\"name\":\"POD_NAMESPACE\",\"valueFrom\":{\"fieldRef\":{\"fieldPath\":\"metadata.namespace\"}}}],\"command\":[\"bash\",\"-c\",\"/usr/bin/dtstack/clone-mysql.sh\"],\"volumeMounts\":[{\"name\":\"mysql-data\",\"mountPath\":\"/var/lib/mysql\",\"subPath\":\"mysql\"},{\"name\":\"mysql-conf\",\"mountPath\":\"/etc/mysql/conf.d\"}]}', 3);
INSERT INTO `workload_step` VALUES (17, 'mysql-sts', 'container', 'bound', '{\"image\":\"mysql:5.7.32_02\",\"imagePullPolicy\":\"Always\",\"env\":[{\"name\":\"MYSQL_ALLOW_EMPTY_PASSWORD\",\"value\":\"1\"}],\"ports\":[{\"name\":\"mysql\",\"containerPort\":3306}],\"volumeMounts\":[{\"name\":\"mysql-data\",\"mountPath\":\"/var/lib/mysql\",\"subPath\":\"mysql\"},{\"name\":\"mysql-conf\",\"mountPath\":\"/etc/mysql/conf.d\"}],\"resources\":{\"requests\":{\"memory\":\"1Gi\",\"cpu\":\"1\"},\"limits\":{\"memory\":\"3Gi\",\"cpu\":\"3\"}},\"livenessProbe\":{\"exec\":{\"command\":[\"sh\",\"-c\",\"/usr/bin/dtstack/mysql-liveness.sh\"]},\"initialDelaySeconds\":30,\"periodSeconds\":10,\"timeoutSeconds\":5},\"readinessProbe\":{\"exec\":{\"command\":[\"sh\",\"-c\",\"/usr/bin/dtstack/mysql-liveness.sh\"]},\"initialDelaySeconds\":30,\"periodSeconds\":2,\"timeoutSeconds\":1}}', 3);
INSERT INTO `workload_step` VALUES (18, 'mysql-svc', 'service', 'createorupdate', '{\"spec\":{\"ports\":[{\"name\":\"mysql\",\"port\":3306,\"targetPort\":3306,\"protocol\":\"TCP\"},{\"name\":\"mysql-exporter\",\"port\":9104,\"protocol\":\"TCP\",\"targetPort\":9104}],\"clusterIP\":\"None\",\"selector\":{\"app\":\"@master-slave\"}}}', 3);
INSERT INTO `workload_step` VALUES (19, 'pushgatewaylocaltime', 'volume', 'bound', '{\"hostPath\":{\"path\":\"/etc/localtime\"}}', 4);
INSERT INTO `workload_step` VALUES (20, 'pushgateway-dp', 'container', 'bound', '{\"image\":\"pushgateway:v1.3.1_01\",\"readinessProbe\":{\"initialDelaySeconds\":10,\"timeoutSeconds\":5,\"httpGet\":{\"path\":\"/#/status\",\"port\":9091}},\"livenessProbe\":{\"initialDelaySeconds\":10,\"timeoutSeconds\":5,\"httpGet\":{\"path\":\"/#/status\",\"port\":9091}},\"resources\":{\"requests\":{\"memory\":\"1Gi\",\"cpu\":\"1\"},\"limits\":{\"memory\":\"3Gi\",\"cpu\":\"3\"}},\"ports\":[{\"containerPort\":9091}],\"volumeMounts\":[{\"name\":\"pushgatewaylocaltime\",\"mountPath\":\"/etc/localtime\"}]}', 4);
INSERT INTO `workload_step` VALUES (21, 'pushgateway-svc', 'service', 'createorupdate', '{\"metadata\":{\"annotations\":{\"prometheus.io/scrape\":\"true\",\"prometheus.io/port\":\"9091\"}},\"spec\":{\"ports\":[{\"name\":\"pushgateway\",\"port\":9091,\"targetPort\":9091}],\"selector\":{\"app\":\"@singlenode\"}}}', 4);
INSERT INTO `workload_step` VALUES (22, 'prometheus-data', 'pvc', 'bound', '{\"spec\":{\"storageClassName\":\"local-storage-workload-prometheus\",\"accessModes\":[\"ReadWriteOnce\"],\"resources\":{\"requests\":{\"storage\":\"5G\"}}}}', 5);
INSERT INTO `workload_step` VALUES (23, 'prometheus-cm', 'conf', 'createorupdate', '{\"data\":{\"prometheus.yml\":\"# my global config\\nglobal:\\n  scrape_interval:     15s\\n  evaluation_interval: 15s\\n  # scrape_timeout is set to the global default (10s).\\n\\nalerting:\\n  alertmanagers:\\n  - static_configs:\\n    - targets:\\n      # - alertmanager:9093\\n\\nrule_files:\\n  # - \\\"first_rules.yml\\\"\\n  # - \\\"second_rules.yml\\\"\\n\\nscrape_configs:\\n  - job_name: \'prometheus\'\\n    static_configs:\\n    - targets: [\'localhost:9090\']\\n  - job_name: \'pushgateway\'\\n    static_configs:\\n    - targets: [\'localhost:9091\']\\n\"}}', 5);
INSERT INTO `workload_step` VALUES (24, 'prome-localtime', 'volume', 'bound', '{\"hostPath\":{\"path\":\"/etc/localtime\"}}', 5);
INSERT INTO `workload_step` VALUES (25, 'prome-cmvolume', 'volume', 'bound', '{\"configMap\":{\"name\":\"@prometheus-cm\"}}', 5);
INSERT INTO `workload_step` VALUES (26, 'prometheus-sts', 'container', 'bound', '{\"image\":\"prometheus:v2.23.0_01\",\"resources\":{\"requests\":{\"memory\":\"1Gi\",\"cpu\":\"1\"},\"limits\":{\"memory\":\"3Gi\",\"cpu\":\"3\"}},\"ports\":[{\"containerPort\":9090,\"name\":\"prom-server\"}],\"command\":[\"/bin/prometheus\"],\"args\":[\"--config.file=/etc/prometheus/prometheus.yml\",\"--storage.tsdb.path=/data/prometheus\",\"--storage.tsdb.retention=24h\",\"--web.enable-admin-api\",\"--web.enable-lifecycle\"],\"readinessProbe\":{\"httpGet\":{\"path\":\"/-/ready\",\"port\":9090},\"initialDelaySeconds\":10,\"timeoutSeconds\":5},\"livenessProbe\":{\"httpGet\":{\"path\":\"/-/healthy\",\"port\":9090},\"initialDelaySeconds\":10,\"timeoutSeconds\":5},\"volumeMounts\":[{\"name\":\"prome-localtime\",\"mountPath\":\"/etc/localtime\"},{\"name\":\"prometheus-data\",\"mountPath\":\"/data/prometheus\"},{\"name\":\"prome-cmvolume\",\"mountPath\":\"/etc/prometheus\"}],\"securityContext\":{\"runAsUser\":0,\"runAsGroup\":0}}', 5);
INSERT INTO `workload_step` VALUES (27, 'prometheus-svc', 'service', 'createorupdate', '{\"spec\":{\"ports\":[{\"port\":9090,\"name\":\"prometheus\",\"targetPort\":9090}],\"selector\":{\"app\":\"@master\"}}}', 5);
INSERT INTO `workload_step` VALUES (28, 'kafka-sts', 'container', 'bound', '{\"image\":\"kafka:1.1.1_01\",\"resources\":{\"requests\":{\"memory\":\"1Gi\",\"cpu\":\"1\"},\"limits\":{\"memory\":\"3Gi\",\"cpu\":\"3\"}},\"ports\":[{\"containerPort\":9092,\"name\":\"kafka-server\"}],\"env\":[{\"name\":\"KAFKA_HEAP_OPTS\",\"value\":\"-Xmx256M -Xms256M\"},{\"name\":\"KAFKA_OPTS\",\"value\":\"-Dlogging.level=INFO\"},{\"name\":\"POD_NAMESPACE\",\"valueFrom\":{\"fieldRef\":{\"fieldPath\":\"metadata.namespace\"}}}],\"command\":[\"bash\",\"-c\",\"exec kafka-server-start.sh /opt/dtstack/kafka/config/server.properties --override broker.id=${HOSTNAME##*-} --override zookeeper.connect=dtbase-zookeeper-leader-0.dtbase-zookeeper-leader-zk-hs.$POD_NAMESPACE.svc.cluster.local:2181,dtbase-zookeeper-leader-1.dtbase-zookeeper-leader-zk-hs.$POD_NAMESPACE.svc.cluster.local:2181,dtbase-zookeeper-leader-2.dtbase-zookeeper-leader-zk-hs.$POD_NAMESPACE.svc.cluster.local:2181/streamtest --override listeners=PLAINTEXT://:9092\"],\"securityContext\":{\"runAsUser\":1000,\"runAsGroup\":1000}}', 6);
INSERT INTO `workload_step` VALUES (29, 'kafka-svc', 'service', 'createorupdate', '{\"spec\":{\"ports\":[{\"port\":9090,\"name\":\"prometheus\",\"targetPort\":9090}],\"selector\":{\"app\":\"@master\"}}}', 6);
INSERT INTO `workload_step` VALUES (30, 'mysql-xtrabackup', 'container', 'bound', '{\"image\":\"xtrabackup:2.4.21_02\",\"env\":[{\"name\":\"POD_NAMESPACE\",\"valueFrom\":{\"fieldRef\":{\"fieldPath\":\"metadata.namespace\"}}}],\"ports\":[{\"name\":\"xtrabackup\",\"containerPort\":3307}],\"command\":[\"bash\",\"-c\",\"/usr/bin/dtstack/xtrabackup.sh\"],\"volumeMounts\":[{\"name\":\"mysql-data\",\"mountPath\":\"/var/lib/mysql\",\"subPath\":\"mysql\"},{\"name\":\"mysql-conf\",\"mountPath\":\"/etc/mysql/conf.d\"}],\"resources\":{\"requests\":{\"memory\":\"100Mi\",\"cpu\":\"100m\"}}}', 3);
INSERT INTO `workload_step` VALUES (31, 'mysql-exporter', 'container', 'bound', '{\"image\":\"mysqld-exporter:v0.12.1_01\",\"env\":[{\"name\":\"DATA_SOURCE_NAME\",\"value\":\"monitor:Abc123Admini@(127.0.0.1:3306)/\"}],\"ports\":[{\"protocol\":\"TCP\",\"containerPort\":9104}]}', 3);
COMMIT;

UPDATE `import_init_moudle` SET operator = '{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"name\":\"mole-operator\",\"namespace\":\"{{.NAME_SPACE}}\"},\"spec\":{\"replicas\":1,\"selector\":{\"matchLabels\":{\"name\":\"mole-operator\"}},\"template\":{\"metadata\":{\"labels\":{\"name\":\"mole-operator\"}},\"spec\":{\"containers\":[{\"command\":[\"mole-operator\"],\"env\":[{\"name\":\"WATCH_NAMESPACE\",\"value\":\"{{.NAME_SPACE}}\"},{\"name\":\"LOG_MEM_LIMIT\",\"value\":\"500Mi\"},{\"name\":\"LOG_CPU_LIMIT\",\"value\":\"100m\"},{\"name\":\"LOG_MEM_REQUEST\",\"value\":\"200Mi\"},{\"name\":\"LOG_CPU_REQUEST\",\"value\":\"10m\"},{\"name\":\"POD_NAME\",\"valueFrom\":{\"fieldRef\":{\"fieldPath\":\"metadata.name\"}}},{\"name\":\"OPERATOR_NAME\",\"value\":\"mole-operator\"}],\"image\":\"{{.REGISTRY}}/mole:v4.1.2\",\"imagePullPolicy\":\"Always\",\"name\":\"mole-operator\",\"resources\":{\"limits\":{\"cpu\":\"500m\",\"memory\":\"500Mi\"}}}],\"imagePullSecrets\":[{\"name\":\"{{.SECRET_NAME}}\"}]}}}}';

ALTER TABLE import_init_moudle ADD COLUMN `log_config` varchar(2000) DEFAULT "" AFTER `operator`;

UPDATE `import_init_moudle` SET log_config = '{\"apiVersion\":\"v1\",\"data\":{\"filebeat.yml\":\"logging.level: debug\\nfilebeat.inputs:\\n  - type: log\\n    tail_files: true\\n    index: \\\"log-${PRODUCT}-%{+yyyy-MM-dd}\\\"\\n    fields:\\n      namespace: ${NAMESPACE}\\n      serviceAccountName: ${SERVICE_ACCOUNT_NAME}\\n      product: ${PRODUCT}\\n      job: ${JOB}\\n      node: ${HOSTNAME}/${HOST_IP}\\n      pod_name: ${POD_NAME}\\n      pod_uid: ${POD_UID}\\n      pod_ip: ${POD_IP}\\n    tags: [ \\\"${PRODUCT}\\\",\\\"${JOB}\\\" ]\\n    paths: ${LOG_PATH}\\noutput.elasticsearch:\\n  hosts: [ \\\"${LOG_SERVER_ADDRESS}\\\" ]\\n  username: \\\"elastic\\\"\\n  password: \\\"dtstack\\\"\\n\",\"promtail.yaml\":\"client:\\n  backoff_config:\\n    max_period: 5m\\n    max_retries: 10\\n    min_period: 500ms\\n  batchsize: 1048576\\n  batchwait: 1s\\n  external_labels: {}\\n  timeout: 10s\\npositions:\\n  filename: /run/positions.yaml\\nserver:\\n  http_listen_port: 3101\\ntarget_config:\\n  sync_period: 10s\\nscrape_configs:\\n  - job_name: test\\n    static_configs:\\n      - labels:\\n          namespace: ${NAMESPACE}\\n          serviceAccountName: ${SERVICE_ACCOUNT_NAME}\\n          product: ${PRODUCT}\\n          job: ${JOB}\\n          node: ${HOSTNAME}/${HOST_IP}\\n          pod_name: ${POD_NAME}\\n          pod_uid: ${POD_UID}\\n          pod_ip: ${POD_IP}\\n          __path__: ${LOG_PATH}\\n\"},\"kind\":\"ConfigMap\",\"metadata\":{\"name\":\"log-configmap\",\"namespace\":\"{{.NAME_SPACE}}\"}}';
