CREATE TABLE IF NOT EXISTS `inspect_report_template` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `cluster_id` int(11) NOT NULL COMMENT '集群id',
  `type` tinyint(1) NOT NULL COMMENT '图表所属类型，0为节点，1为应用',
  `module` varchar(255) NOT NULL COMMENT '模块',
  `metric` varchar(255) NOT NULL COMMENT '指标',
  `targets` text NOT NULL COMMENT '采集数据配置，数组类型，包含查询语句以及维度拼接模板',
  `unit` varchar(16) DEFAULT '' COMMENT 'y轴单位',
  `decimal` int(11) DEFAULT 0 COMMENT 'y轴小数点保留位数',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  PRIMARY KEY(`id`)
) COMMENT '巡检报告图表自定义模板' ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `deploy_schema_multi_fields` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `cluster_id` int(11) NOT NULL COMMENT '集群id',
  `product_name` varchar(255) NOT NULL DEFAULT '' COMMENT '产品名称',
  `service_name` varchar(255) NOT NULL DEFAULT '' COMMENT '服务名称',
  `field_path` varchar(255) NOT NULL DEFAULT '' COMMENT '字段路径',
  `field` text NOT NULL COMMENT '字段值',
  `hosts` varchar(255) NOT NULL COMMENT '配置绑定主机ip，逗号连接',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY(`id`),
  UNIQUE KEY `namesz_path` (`product_name`, `service_name`, `field_path`, `hosts`)
) COMMENT 'schema配置多值记录' ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `deploy_notify_event` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `cluster_id` int(11) NOT NULL COMMENT '集群id',
  `type` tinyint(1) NOT NULL COMMENT '事件类型，0表示配置变更依赖组件重启',
  `product_name` varchar(255) DEFAULT NULL COMMENT '产品名称',
  `service_name` varchar(255) DEFAULT NULL COMMENT '服务名称',
  `depend_product_name` varchar(255) DEFAULT NULL COMMENT '被依赖的产品名称',
  `depend_service_name` varchar(255) DEFAULT NULL COMMENT '被依赖的服务名称',
  `host` varchar(1024) DEFAULT NULL COMMENT '主机ip',
  `is_deleted` tinyint(1) DEFAULT 0 COMMENT '是否删除',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY(`id`)
) COMMENT '通知事件' ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (1, 1, 0, 'System', 'System Load', '[{\"expr\":\"node_load1{}\",\"legend_format\":\"Load1-{{instance}}\"}]', '', 2, '2021-03-30 11:32:29', '2021-03-30 11:32:29', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (2, 1, 0, 'System', 'Disk Used(%)', '[{\"expr\":\"100-100*((node_filesystem_avail{device=~\\\"/dev/.*\\\",mountpoint!=\\\"/boot\\\"}/node_filesystem_size{device=~\\\"/dev/.*\\\",mountpoint!=\\\"/boot\\\"}))\",\"legend_format\":\"DiskUsed-{{instance}}{{mountpoint}}\"}]', '%', 0, '2021-03-30 13:56:00', '2021-03-30 13:56:00', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (3, 1, 0, 'System', 'Inode Used(%)', '[{\"expr\":\"100*((node_filesystem_files{device=~\\\"/dev/.*\\\",mountpoint!=\\\"/boot\\\"}-node_filesystem_files_free{device=~\\\"/dev/.*\\\",mountpoint!=\\\"/boot\\\"})/node_filesystem_files{device=~\\\"/dev/.*\\\",mountpoint!=\\\"/boot\\\"})\",\"legend_format\":\"InodeUsed-{{instance}}{{mountpoint}}\"}]', '%', 3, '2021-03-30 14:02:11', '2021-03-30 14:02:11', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (4, 1, 0, 'System', 'Mem Used(%)', '[{\"expr\":\"(1 - (sum by (instance) (node_memory_MemFree + node_memory_Buffers + node_memory_Cached)) / (sum by (instance) (node_memory_MemTotal)) ) * 100\",\"legend_format\":\"MemUsed-{{instance}}\"}]', '%', 0, '2021-03-30 14:02:52', '2021-03-30 14:02:52', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (5, 1, 0, 'System', 'Node_up', '[{\"expr\":\"up{job=\\\"node_exporter\\\"}\",\"legend_format\":\"{{instance}}\"}]', '', 0, '2021-03-30 14:07:10', '2021-03-30 14:07:10', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (6, 1, 0, 'MySQL', 'MySQL down-监控', '[{\"expr\":\"up{product_name=\\\"DTBase\\\",service_name=\\\"mysql\\\"}\",\"legend_format\":\"{{instance}}\"}]', '', 0, '2021-04-01 16:34:25', '2021-04-01 16:34:25', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (7, 1, 0, 'MySQL', 'MySQL Connection', '[{\"expr\":\"max(max_over_time(mysql_global_status_threads_connected{product_name=\\\"DTBase\\\",service_name=\\\"mysql\\\"}[1m])or mysql_global_status_threads_connected{product_name=\\\"DTBase\\\",service_name=\\\"mysql\\\"})\",\"legend_format\":\"Connections\"},{\"expr\":\"mysql_global_status_max_used_connections{product_name=\\\"DTBase\\\",service_name=\\\"mysql\\\"}\",\"legend_format\":\"MaxUsedConnections\"},{\"expr\":\"mysql_global_variables_max_connections{product_name=\\\"DTBase\\\",service_name=\\\"mysql\\\"}\",\"legend_format\":\"MaxConnections\"}]', '', 0, '2021-04-01 16:36:42', '2021-04-01 16:36:42', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (8, 1, 0, 'MySQL', 'MySQL Slow Queries', '[{\"expr\":\"rate(mysql_global_status_slow_queries{product_name=\\\"DTBase\\\",service_name=\\\"mysql\\\"}[1m])or irate(mysql_global_status_slow_queries{product_name=\\\"DTBase\\\",service_name=\\\"mysql\\\"}[5m])\",\"legend_format\":\"{{instance}}-SlowQueries\"}]', '', 1, '2021-04-01 17:06:57', '2021-04-01 17:06:57', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (9, 1, 0, 'Zookeeper', 'Zookeeper up', '[{\"expr\":\"up{product_name=\\\"DTBase\\\",service_name=\\\"zookeeper\\\"}\",\"legend_format\":\"{{instance}}\"}]', '', 0, '2021-04-01 17:14:23', '2021-04-01 17:14:23', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (10, 1, 0, 'Zookeeper', 'Old Gen Used(%)', '[{\"expr\":\"100*jvm_memory_pool_bytes_used{pool=\\\"PS Old Gen\\\",product_name=\\\"DTBase\\\",service_name=\\\"zookeeper\\\"}/jvm_memory_pool_bytes_committed{pool=\\\"PS Old Gen\\\",product_name=\\\"DTBase\\\",service_name=\\\"zookeeper\\\"}\",\"legend_format\":\"OldGenUsed-{{instance}}\"}]', '%', 2, '2021-04-01 17:28:24', '2021-04-01 17:28:24', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (11, 1, 0, 'Zookeeper', 'Heap Used(%)', '[{\"expr\":\"100*jvm_memory_bytes_used{area=\\\"heap\\\",product_name=\\\"DTBase\\\",service_name=\\\"zookeeper\\\"}/jvm_memory_bytes_committed{area=\\\"heap\\\",product_name=\\\"DTBase\\\",service_name=\\\"zookeeper\\\"}\",\"legend_format\":\"HeapUsed-{{instance}}\"}]', '%', 2, '2021-04-01 17:45:34', '2021-04-01 17:45:34', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (12, 1, 0, 'Zookeeper', 'Full GC Count（2minutes）', '[{\"expr\":\"floor(delta(jvm_gc_collection_seconds_count{gc=\\\"PS MarkSweep\\\",product_name=\\\"DTBase\\\",service_name=\\\"zookeeper\\\"}[2m]))\",\"legend_format\":\"FullGCCount-{{instance}}\"}]', '', 0, '2021-04-01 18:00:22', '2021-04-01 18:00:22', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (13, 1, 0, 'Zookeeper', 'Full GC Avg Time', '[{\"expr\":\"(jvm_gc_collection_seconds_sum{gc=\\\"PS MarkSweep\\\",product_name=\\\"DTBase\\\",service_name=\\\"zookeeper\\\"} > 0 or on() vector(0.001)) or (jvm_gc_collection_seconds_sum{gc=\\\"PS MarkSweep\\\",product_name=\\\"DTBase\\\",service_name=\\\"zookeeper\\\"} > bool 0)/(jvm_gc_collection_seconds_count{gc=\\\"PS MarkSweep\\\",product_name=\\\"DTBase\\\",service_name=\\\"zookeeper\\\"} > 0 or on() vector(1)) or (jvm_gc_collection_seconds_count{gc=\\\"PS MarkSweep\\\",product_name=\\\"DTBase\\\",service_name=\\\"zookeeper\\\"} > bool 0)\",\"legend_format\":\"FullGCAvgTime-{{instance}}\"}]', '', 3, '2021-04-01 18:04:04', '2021-04-01 18:04:04', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (14, 1, 0, 'Zookeeper', 'Full GC Count', '[{\"expr\":\"jvm_gc_collection_seconds_count{gc=\\\"PS MarkSweep\\\",product_name=\\\"DTBase\\\",service_name=\\\"zookeeper\\\"}\",\"legend_format\":\"FullGCCount-{{instance}}\"}]', '', 2, '2021-04-01 18:05:20', '2021-04-01 18:05:20', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (15, 1, 0, 'Redis', 'Redis_Up', '[{\"expr\":\"up{product_name=\\\"DTBase\\\",service_name=\\\"redis\\\"}\",\"legend_format\":\"{{instance}}\"}]', '', 0, '2021-04-01 19:25:28', '2021-04-01 19:25:28', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (16, 1, 0, 'NameNode', 'NameNode_up', '[{\"expr\":\"up{product_name=\\\"Hadoop\\\",service_name=\\\"hdfs_namenode\\\"}\",\"legend_format\":\"{{instance}}\"}]', '', 0, '2021-04-02 15:08:07', '2021-04-02 15:08:07', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (17, 1, 0, 'NameNode', 'Old Gen Used(%)', '[{\"expr\":\"100*jvm_memory_pool_bytes_used{pool=\\\"PS Old Gen\\\",product_name=\\\"Hadoop\\\",service_name=\\\"hdfs_namenode\\\"}/jvm_memory_pool_bytes_committed{pool=\\\"PS Old Gen\\\",product_name=\\\"Hadoop\\\",service_name=\\\"hdfs_namenode\\\"}\",\"legend_format\":\"OldGenUsed-{{instance}}\"}]', '%', 2, '2021-04-02 15:10:27', '2021-04-02 15:10:27', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (18, 1, 0, 'NameNode', 'Heap Used(%)', '[{\"expr\":\"100*jvm_memory_bytes_used{area=\\\"heap\\\",product_name=\\\"Hadoop\\\",service_name=\\\"hdfs_namenode\\\"}/jvm_memory_bytes_committed{area=\\\"heap\\\",product_name=\\\"Hadoop\\\",service_name=\\\"hdfs_namenode\\\"}\",\"legend_format\":\"HeapUsed-{{instance}}\"}]', '%', 2, '2021-04-02 15:11:55', '2021-04-02 15:11:55', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (19, 1, 0, 'NameNode', 'Full GC Count(2 minutes)', '[{\"expr\":\"floor(delta(jvm_gc_collection_seconds_count{gc=\\\"PS MarkSweep\\\",product_name=\\\"Hadoop\\\",service_name=\\\"hdfs_namenode\\\"}[2m]))\",\"legend_format\":\"FullGCCount-{{instance}}\"}]', '', 0, '2021-04-02 15:16:06', '2021-04-02 15:16:06', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (20, 1, 0, 'NameNode', 'Full GC Avg Time', '[{\"expr\":\"jvm_gc_collection_seconds_sum{gc=\\\"PS MarkSweep\\\",product_name=\\\"Hadoop\\\",service_name=\\\"hdfs_namenode\\\"}/jvm_gc_collection_seconds_count{gc=\\\"PS MarkSweep\\\",product_name=\\\"Hadoop\\\",service_name=\\\"hdfs_namenode\\\"}\",\"legend_format\":\"FullGCAvgTime-{{instance}}\"}]', '', 3, '2021-04-02 15:17:27', '2021-04-02 15:17:27', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (21, 1, 0, 'NameNode', 'Total/Used', '[{\"expr\":\"Hadoop_NameNode_Total{name=\\\"NameNodeInfo\\\",product_name=\\\"Hadoop\\\",service_name=\\\"hdfs_namenode\\\"}\",\"legend_format\":\"Total-{{instance}}\"},{\"expr\":\"Hadoop_NameNode_Used{name=\\\"NameNodeInfo\\\",product_name=\\\"Hadoop\\\",service_name=\\\"hdfs_namenode\\\"}\",\"legend_format\":\"Used-{{instance}}\"}]', '', 3, '2021-04-02 15:31:46', '2021-04-02 15:31:46', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (22, 1, 0, 'NameNode', 'TotalBlocks', '[{\"expr\":\"Hadoop_NameNode_TotalBlocks{name=\\\"NameNodeInfo\\\",product_name=\\\"Hadoop\\\",service_name=\\\"hdfs_namenode\\\"}\",\"legend_format\":\"TotalBlocks-{{instance}}\"}]', '', 0, '2021-04-02 15:32:08', '2021-04-02 15:32:08', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (23, 1, 0, 'NameNode', 'Number Of MissingBlocks', '[{\"expr\":\"Hadoop_NameNode_NumberOfMissingBlocks{name=\\\"NameNodeInfo\\\",product_name=\\\"Hadoop\\\",service_name=\\\"hdfs_namenode\\\"}\",\"legend_format\":\"NumberOfMissingBlocks-{{instance}}\"}]', '', 0, '2021-04-02 15:34:20', '2021-04-02 15:34:20', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (24, 1, 0, 'NameNode', 'TotalFiles', '[{\"expr\":\"Hadoop_NameNode_TotalFiles{name=\\\"FSNamesystem\\\",product_name=\\\"Hadoop\\\",service_name=\\\"hdfs_namenode\\\"}\",\"legend_format\":\"TotalFiles-{{instance}}\"}]', '', 0, '2021-04-02 15:38:10', '2021-04-02 15:38:10', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (25, 1, 0, 'NameNode', 'CorruptBlocks', '[{\"expr\":\"Hadoop_NameNode_CorruptBlocks{name=\\\"FSNamesystem\\\",product_name=\\\"Hadoop\\\",service_name=\\\"hdfs_namenode\\\"}\",\"legend_format\":\"CorruptBlocks-{{instance}}\"}]', '', 0, '2021-04-02 15:43:24', '2021-04-02 15:43:24', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (26, 1, 0, 'DataNode', 'DataNode_up', '[{\"expr\":\"up{product_name=\\\"Hadoop\\\",service_name=\\\"hdfs_datanode\\\"}\",\"legend_format\":\"{{instance}}\"}]', '', 0, '2021-04-02 15:48:02', '2021-04-02 15:48:02', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (27, 1, 0, 'DataNode', 'Old Gen Used(%)', '[{\"expr\":\"100*jvm_memory_pool_bytes_used{pool=\\\"PS Old Gen\\\",product_name=\\\"Hadoop\\\",service_name=\\\"hdfs_datanode\\\"}/jvm_memory_pool_bytes_committed{pool=\\\"PS Old Gen\\\",product_name=\\\"Hadoop\\\",service_name=\\\"hdfs_datanode\\\"}\",\"legend_format\":\"OldGenUsed-{{instance}}\"}]', '%', 2, '2021-04-02 15:48:19', '2021-04-02 15:48:19', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (28, 1, 0, 'DataNode', 'Heap Used(%)', '[{\"expr\":\"100*jvm_memory_bytes_used{area=\\\"heap\\\",product_name=\\\"Hadoop\\\",service_name=\\\"hdfs_datanode\\\"}/jvm_memory_bytes_committed{area=\\\"heap\\\",product_name=\\\"Hadoop\\\",service_name=\\\"hdfs_datanode\\\"}\",\"legend_format\":\"HeapUsed-{{instance}}\"}]', '%', 2, '2021-04-02 15:49:53', '2021-04-02 15:49:53', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (29, 1, 0, 'DataNode', 'Full GC Count(2 minutes)', '[{\"expr\":\"floor(delta(jvm_gc_collection_seconds_count{gc=\\\"PS MarkSweep\\\",product_name=\\\"Hadoop\\\",service_name=\\\"hdfs_datanode\\\"}[2m]))\",\"legend_format\":\"FullGCCount-{{instance}}\"}]', '', 0, '2021-04-02 15:58:04', '2021-04-02 15:58:04', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (30, 1, 0, 'DataNode', 'Full GC Avg Time', '[{\"expr\":\"jvm_gc_collection_seconds_sum{gc=\\\"PS MarkSweep\\\",product_name=\\\"Hadoop\\\",service_name=\\\"hdfs_datanode\\\"}/jvm_gc_collection_seconds_count{gc=\\\"PS MarkSweep\\\",product_name=\\\"Hadoop\\\",service_name=\\\"hdfs_datanode\\\"}\",\"legend_format\":\"FullGCAvgTime-{{instance}}\"}]', '', 3, '2021-04-02 16:03:55', '2021-04-02 16:03:55', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (31, 1, 0, 'ResourceManager', 'ResourceManager_up', '[{\"expr\":\"up{product_name=\\\"Hadoop\\\",service_name=\\\"yarn_resourcemanager\\\"}\",\"legend_format\":\"{{instance}}\"}]', '', 0, '2021-04-02 17:07:18', '2021-04-02 17:07:18', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (32, 1, 0, 'ResourceManager', 'Old Gen Used(%)', '[{\"expr\":\"100*jvm_memory_pool_bytes_used{pool=\\\"PS Old Gen\\\",product_name=\\\"Hadoop\\\",service_name=\\\"yarn_resourcemanager\\\"}/jvm_memory_pool_bytes_committed{pool=\\\"PS Old Gen\\\",product_name=\\\"Hadoop\\\",service_name=\\\"yarn_resourcemanager\\\"}\",\"legend_format\":\"OldGenUsed-{{instance}}\"}]', '%', 2, '2021-04-02 17:10:48', '2021-04-02 17:10:48', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (33, 1, 0, 'ResourceManager', 'Heap Used(%)', '[{\"expr\":\"100*jvm_memory_bytes_used{area=\\\"heap\\\",product_name=\\\"Hadoop\\\",service_name=\\\"yarn_resourcemanager\\\"}/jvm_memory_bytes_committed{area=\\\"heap\\\",product_name=\\\"Hadoop\\\",service_name=\\\"yarn_resourcemanager\\\"}\",\"legend_format\":\"HeapUsed-{{instance}}\"}]', '%', 2, '2021-04-02 17:15:26', '2021-04-02 17:15:26', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (34, 1, 0, 'ResourceManager', 'Full GC Count(2 minutes)', '[{\"expr\":\"floor(delta(jvm_gc_collection_seconds_count{gc=\\\"PS MarkSweep\\\",product_name=\\\"Hadoop\\\",service_name=\\\"yarn_resourcemanager\\\"}[2m]))\",\"legend_format\":\"FullGCCount-{{instance}}\"}]', '', 0, '2021-04-13 17:04:11', '2021-04-13 17:04:11', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (35, 1, 0, 'ResourceManager', 'Full GC AvgTime', '[{\"expr\":\"jvm_gc_collection_seconds_sum{gc=\\\"PS MarkSweep\\\",product_name=\\\"Hadoop\\\",service_name=\\\"yarn_resourcemanager\\\"}/jvm_gc_collection_seconds_count{gc=\\\"PS MarkSweep\\\",product_name=\\\"Hadoop\\\",service_name=\\\"yarn_resourcemanager\\\"}\",\"legend_format\":\"FullGCTimeAvg-{{instance}}\"}]', '', 3, '2021-04-13 17:07:03', '2021-04-13 17:07:03', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (36, 1, 0, 'ResourceManager', 'NumActiveNMs', '[{\"expr\":\"Hadoop_ResourceManager_NumActiveNMs{name=\\\"ClusterMetrics\\\",product_name=\\\"Hadoop\\\",service_name=\\\"yarn_resourcemanager\\\"}\",\"legend_format\":\"NumActiveNMs-{{instance}}\"}]', '', 0, '2021-04-13 17:09:48', '2021-04-13 17:09:48', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (37, 1, 0, 'ResourceManager', 'NumUnhealthyNMs', '[{\"expr\":\"Hadoop_ResourceManager_NumUnhealthyNMs{name=\\\"ClusterMetrics\\\",product_name=\\\"Hadoop\\\",service_name=\\\"yarn_resourcemanager\\\"}\",\"legend_format\":\"NumUnhealthyeNMs-{{instance}}\"}]', '', 0, '2021-04-13 17:12:18', '2021-04-13 17:12:18', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (38, 1, 0, 'ResourceManager', 'NumLostNMs', '[{\"expr\":\"Hadoop_ResourceManager_NumLostNMs{name=\\\"ClusterMetrics\\\",product_name=\\\"Hadoop\\\",service_name=\\\"yarn_resourcemanager\\\"}\",\"legend_format\":\"NumLostNMs-{{instance}}\"}]', '', 0, '2021-04-13 17:14:01', '2021-04-13 17:14:01', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (39, 1, 0, 'ThriftServer', 'Spark_ThriftServer_Up', '[{\"expr\":\"up{product_name=\\\"Hadoop\\\",service_name=\\\"thriftserver\\\"}\",\"legend_format\":\"{{instance}}\"}]', '', 0, '2021-04-07 10:02:53', '2021-04-07 10:02:53', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (40, 1, 0, 'ThriftServer', 'Old Gen Used(%)', '[{\"expr\":\"100*jvm_memory_pool_bytes_used{pool=\\\"PS Old Gen\\\",product_name=\\\"Hadoop\\\",service_name=\\\"thriftserver\\\"}/jvm_memory_pool_bytes_committed{pool=\\\"PS Old Gen\\\",product_name=\\\"Hadoop\\\",service_name=\\\"thriftserver\\\"}\",\"legend_format\":\"OldGenUsed-{{instance}}\"}]', '%', 2, '2021-04-07 10:07:29', '2021-04-07 10:07:29', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (41, 1, 0, 'ThriftServer', 'Heap Used(%)', '[{\"expr\":\"100*jvm_memory_bytes_used{area=\\\"heap\\\",product_name=\\\"Hadoop\\\",service_name=\\\"thriftserver\\\"}/jvm_memory_bytes_committed{area=\\\"heap\\\",product_name=\\\"Hadoop\\\",service_name=\\\"thriftserver\\\"}\",\"legend_format\":\"HeapUsed-{{instance}}\"}]', '%', 2, '2021-04-07 10:07:56', '2021-04-07 10:07:56', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (42, 1, 0, 'ThriftServer', 'Full GC Count(2 minutes)', '[{\"expr\":\"floor(delta(jvm_gc_collection_seconds_count{gc=\\\"PS MarkSweep\\\",product_name=\\\"Hadoop\\\",service_name=\\\"thriftserver\\\"}[2m]))\",\"legend_format\":\"FullGCCount-{{instance}}\"}]', '', 0, '2021-04-07 10:08:30', '2021-04-07 10:08:30', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (43, 1, 0, 'ThriftServer', 'Full GC Avg Time', '[{\"expr\":\"jvm_gc_collection_seconds_sum{gc=\\\"PS MarkSweep\\\",product_name=\\\"Hadoop\\\",service_name=\\\"thriftserver\\\"}/jvm_gc_collection_seconds_count{gc=\\\"PS MarkSweep\\\",product_name=\\\"Hadoop\\\",service_name=\\\"thriftserver\\\"}\",\"legend_format\":\"FullGCAvgTime-{{instance}}\"}]', 's', 3, '2021-04-07 10:08:57', '2021-04-07 10:08:57', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (44, 1, 0, 'ThriftServer', 'Full GC Count(total)', '[{\"expr\":\"jvm_gc_collection_seconds_count{gc=\\\"PS MarkSweep\\\",product_name=\\\"Hadoop\\\",service_name=\\\"thriftserver\\\"}\",\"legend_format\":\"FullGCCount-{{instance}}\"}]', '', 0, '2021-04-07 10:09:19', '2021-04-07 10:09:19', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (45, 1, 0, 'DTApi', 'API_up', '[{\"expr\":\"up{product_name=\\\"DTApi\\\",service_name=\\\"API\\\"}\",\"legend_format\":\"{{instance}}\"}]', '', 0, '2021-04-07 10:18:26', '2021-04-07 10:18:26', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (46, 1, 0, 'DTApi', 'Old Gen Used(%)', '[{\"expr\":\"100*jvm_memory_pool_bytes_used{pool=\\\"G1 Old Gen\\\",product_name=\\\"DTApi\\\",service_name=\\\"API\\\"}/jvm_memory_pool_bytes_committed{pool=\\\"G1 Old Gen\\\",product_name=\\\"DTApi\\\",service_name=\\\"API\\\"}\",\"legend_format\":\"OldGenUsed-{{instance}}\"}]', '%', 2, '2021-04-07 10:19:27', '2021-04-07 10:19:27', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (47, 1, 0, 'DTApi ', 'Heap Used(%)', '[{\"expr\":\"100*jvm_memory_bytes_used{area=\\\"heap\\\",product_name=\\\"DTApi\\\",service_name=\\\"API\\\"}/jvm_memory_bytes_committed{area=\\\"heap\\\",product_name=\\\"DTApi\\\",service_name=\\\"API\\\"}\",\"legend_format\":\"HeapUsed-{{instance}}\"}]', '%', 2, '2021-04-07 10:21:55', '2021-04-07 10:21:55', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (48, 1, 0, 'DTApi', 'Full GC Count(2 minutes)', '[{\"expr\":\"floor(delta(jvm_gc_collection_seconds_count{gc=\\\"G1 Old Generation\\\",product_name=\\\"DTApi\\\",service_name=\\\"API\\\"}[2m]))\",\"legend_format\":\"FullGCCount-{{instance}}\"}]', '', 0, '2021-04-07 10:23:57', '2021-04-07 10:23:57', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (49, 1, 0, 'DTApi', 'Full GC Avg Time', '[{\"expr\":\"jvm_gc_collection_seconds_sum{gc=\\\"G1 Old Generation\\\",product_name=\\\"DTApi\\\",service_name=\\\"API\\\"}/jvm_gc_collection_seconds_count{gc=\\\"G1 Old Generation\\\",product_name=\\\"DTApi\\\",service_name=\\\"API\\\"}\",\"legend_format\":\"FullGCAvgTime-{{instance}}\"}]', '', 0, '2021-04-07 10:25:18', '2021-04-07 10:25:18', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (50, 1, 0, 'DTApi', 'Full GC Count(Total)', '[{\"expr\":\"jvm_gc_collection_seconds_count{gc=\\\"G1 Old Generation\\\",product_name=\\\"DTApi\\\",service_name=\\\"API\\\"}\",\"legend_format\":\"FullGCCount-{{instance}}\"}]', '', 0, '2021-04-07 10:26:20', '2021-04-07 10:26:20', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (51, 1, 0, 'DTBatch', 'Batch_up', '[{\"expr\":\"up{product_name=\\\"DTBatch\\\",service_name=\\\"Batch\\\"}\",\"legend_format\":\"{{instance}}\"}]', '', 0, '2021-04-07 10:18:26', '2021-04-07 10:18:26', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (52, 1, 0, 'DTBatch', 'Old Gen Used(%)', '[{\"expr\":\"100*jvm_memory_pool_bytes_used{pool=\\\"G1 Old Gen\\\",product_name=\\\"DTBatch\\\",service_name=\\\"Batch\\\"}/jvm_memory_pool_bytes_committed{pool=\\\"G1 Old Gen\\\",product_name=\\\"DTBatch\\\",service_name=\\\"Batch\\\"}\",\"legend_format\":\"OldGenUsed-{{instance}}\"}]', '%', 2, '2021-04-07 10:19:27', '2021-04-07 10:19:27', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (53, 1, 0, 'DTBatch ', 'Heap Used(%)', '[{\"expr\":\"100*jvm_memory_bytes_used{area=\\\"heap\\\",product_name=\\\"DTBatch\\\",service_name=\\\"Batch\\\"}/jvm_memory_bytes_committed{area=\\\"heap\\\",product_name=\\\"DTBatch\\\",service_name=\\\"Batch\\\"}\",\"legend_format\":\"HeapUsed-{{instance}}\"}]', '%', 2, '2021-04-07 10:21:55', '2021-04-07 10:21:55', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (54, 1, 0, 'DTBatch', 'Full GC Count(2 minutes)', '[{\"expr\":\"floor(delta(jvm_gc_collection_seconds_count{gc=\\\"G1 Old Generation\\\",product_name=\\\"DTBatch\\\",service_name=\\\"Batch\\\"}[2m]))\",\"legend_format\":\"FullGCCount-{{instance}}\"}]', '', 0, '2021-04-07 10:23:57', '2021-04-07 10:23:57', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (55, 1, 0, 'DTBatch', 'Full GC Avg Time', '[{\"expr\":\"jvm_gc_collection_seconds_sum{gc=\\\"G1 Old Generation\\\",product_name=\\\"DTBatch\\\",service_name=\\\"Batch\\\"}/jvm_gc_collection_seconds_count{gc=\\\"G1 Old Generation\\\",product_name=\\\"DTBatch\\\",service_name=\\\"Batch\\\"}\",\"legend_format\":\"FullGCAvgTime-{{instance}}\"}]', '', 3, '2021-04-07 10:25:18', '2021-04-07 10:25:18', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (56, 1, 0, 'DTBatch', 'Full GC Count(Total)', '[{\"expr\":\"jvm_gc_collection_seconds_count{gc=\\\"G1 Old Generation\\\",product_name=\\\"DTBatch\\\",service_name=\\\"Batch\\\"}\",\"legend_format\":\"FullGCCount-{{instance}}\"}]', '', 0, '2021-04-07 10:26:20', '2021-04-07 10:26:20', 0);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (57, 1, 0, 'DTStream', 'Stream_up', '[{\"expr\":\"up{product_name=\\\"DTStream\\\",service_name=\\\"Stream\\\"}\",\"legend_format\":\"{{instance}}\"}]', '', 0, '2021-04-07 10:18:26', '2021-04-07 10:18:26', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (58, 1, 0, 'DTStream', 'Old Gen Used(%)', '[{\"expr\":\"100*jvm_memory_pool_bytes_used{pool=\\\"G1 Old Gen\\\",product_name=\\\"DTStream\\\",service_name=\\\"Stream\\\"}/jvm_memory_pool_bytes_committed{pool=\\\"G1 Old Gen\\\",product_name=\\\"DTStream\\\",service_name=\\\"Stream\\\"}\",\"legend_format\":\"OldGenUsed-{{instance}}\"}]', '%', 2, '2021-04-07 10:19:27', '2021-04-07 10:19:27', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (59, 1, 0, 'DTStream ', 'Heap Used(%)', '[{\"expr\":\"100*jvm_memory_bytes_used{area=\\\"heap\\\",product_name=\\\"DTStream\\\",service_name=\\\"Stream\\\"}/jvm_memory_bytes_committed{area=\\\"heap\\\",product_name=\\\"DTStream\\\",service_name=\\\"Stream\\\"}\",\"legend_format\":\"HeapUsed-{{instance}}\"}]', '%', 2, '2021-04-07 10:21:55', '2021-04-07 10:21:55', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (60, 1, 0, 'DTStream', 'Full GC Count(2 minutes)', '[{\"expr\":\"floor(delta(jvm_gc_collection_seconds_count{gc=\\\"G1 Old Generation\\\",product_name=\\\"DTStream\\\",service_name=\\\"Stream\\\"}[2m]))\",\"legend_format\":\"FullGCCount-{{instance}}\"}]', '', 0, '2021-04-07 10:23:57', '2021-04-07 10:23:57', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (61, 1, 0, 'DTStream', 'Full GC Avg Time', '[{\"expr\":\"(jvm_gc_collection_seconds_sum{product_name=\\\"DTStream\\\",service_name=\\\"Stream\\\"}>0)/(jvm_gc_collection_seconds_count{product_name=\\\"DTStream\\\",service_name=\\\"Stream\\\"}>0)\",\"legend_format\":\"FullGCAvgTime-{{instance}}\"}]', '', 3, '2021-04-07 10:25:18', '2021-04-07 10:25:18', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (62, 1, 0, 'DTStream', 'Full GC Count(Total)', '[{\"expr\":\"jvm_gc_collection_seconds_count{gc=\\\"G1 Old Generation\\\",product_name=\\\"DTStream\\\",service_name=\\\"Stream\\\"}\",\"legend_format\":\"FullGCCount-{{instance}}\"}]', '', 0, '2021-04-07 10:26:20', '2021-04-07 10:26:20', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (63, 1, 0, 'DTAssets', 'Assets_up', '[{\"expr\":\"up{product_name=\\\"DTAssets\\\",service_name=\\\"Assets\\\"}\",\"legend_format\":\"{{instance}}\"}]', '', 0, '2021-04-07 10:18:26', '2021-04-07 10:18:26', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (64, 1, 0, 'DTAssets', 'Old Gen Used(%)', '[{\"expr\":\"100*jvm_memory_pool_bytes_used{pool=\\\"G1 Old Gen\\\",product_name=\\\"DTAssets\\\",service_name=\\\"Assets\\\"}/jvm_memory_pool_bytes_committed{pool=\\\"G1 Old Gen\\\",product_name=\\\"DTAssets\\\",service_name=\\\"Assets\\\"}\",\"legend_format\":\"OldGenUsed-{{instance}}\"}]', '%', 2, '2021-04-07 10:19:27', '2021-04-07 10:19:27', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (65, 1, 0, 'DTAssets ', 'Heap Used(%)', '[{\"expr\":\"100*jvm_memory_bytes_used{area=\\\"heap\\\",product_name=\\\"DTAssets\\\",service_name=\\\"Assets\\\"}/jvm_memory_bytes_committed{area=\\\"heap\\\",product_name=\\\"DTAssets\\\",service_name=\\\"Assets\\\"}\",\"legend_format\":\"HeapUsed-{{instance}}\"}]', '%', 2, '2021-04-07 10:21:55', '2021-04-07 10:21:55', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (66, 1, 0, 'DTAssets', 'Full GC Count(2 minutes)', '[{\"expr\":\"floor(delta(jvm_gc_collection_seconds_count{gc=\\\"G1 Old Generation\\\",product_name=\\\"DTAssets\\\",service_name=\\\"Assets\\\"}[2m]))\",\"legend_format\":\"FullGCCount-{{instance}}\"}]', '', 0, '2021-04-07 10:23:57', '2021-04-07 10:23:57', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (67, 1, 0, 'DTAssets', 'Full GC Avg Time', '[{\"expr\":\"jvm_gc_collection_seconds_sum{gc=\\\"G1OldGeneration\\\",product_name=\\\"DTAssets\\\",service_name=\\\"Assets\\\"}/jvm_gc_collection_seconds_count{gc=\\\"G1OldGeneration\\\",product_name=\\\"DTAssets\\\",service_name=\\\"Assets\\\"}\",\"legend_format\":\"FullGCAvgTime-{{instance}}\"}]', '', 0, '2021-04-07 10:25:18', '2021-04-07 10:25:18', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (68, 1, 0, 'DTAssets', 'Full GC Count(Total)', '[{\"expr\":\"jvm_gc_collection_seconds_count{gc=\\\"G1 Old Generation\\\",product_name=\\\"DTAssets\\\",service_name=\\\"Assets\\\"}\",\"legend_format\":\"FullGCCount-{{instance}}\"}]', '', 0, '2021-04-07 10:26:20', '2021-04-07 10:26:20', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (69, 1, 0, 'DTConsole', 'Console_up', '[{\"expr\":\"up{product_name=\\\"DTConsole\\\",service_name=\\\"Console\\\"}\",\"legend_format\":\"{{instance}}\"}]', '', 0, '2021-04-07 10:18:26', '2021-04-07 10:18:26', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (70, 1, 0, 'DTConsole', 'Old Gen Used(%)', '[{\"expr\":\"100*jvm_memory_pool_bytes_used{pool=\\\"G1 Old Gen\\\",product_name=\\\"DTConsole\\\",service_name=\\\"Console\\\"}/jvm_memory_pool_bytes_committed{pool=\\\"G1 Old Gen\\\",product_name=\\\"DTConsole\\\",service_name=\\\"Console\\\"}\",\"legend_format\":\"OldGenUsed-{{instance}}\"}]', '%', 2, '2021-04-07 10:19:27', '2021-04-07 10:19:27', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (71, 1, 0, 'DTConsole ', 'Heap Used(%)', '[{\"expr\":\"100*jvm_memory_bytes_used{area=\\\"heap\\\",product_name=\\\"DTConsole\\\",service_name=\\\"Console\\\"}/jvm_memory_bytes_committed{area=\\\"heap\\\",product_name=\\\"DTConsole\\\",service_name=\\\"Console\\\"}\",\"legend_format\":\"HeapUsed-{{instance}}\"}]', '%', 2, '2021-04-07 10:21:55', '2021-04-07 10:21:55', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (72, 1, 0, 'DTConsole', 'Full GC Count(2 minutes)', '[{\"expr\":\"floor(delta(jvm_gc_collection_seconds_count{gc=\\\"G1 Old Generation\\\",product_name=\\\"DTConsole\\\",service_name=\\\"Console\\\"}[2m]))\",\"legend_format\":\"FullGCCount-{{instance}}\"}]', '', 0, '2021-04-07 10:23:57', '2021-04-07 10:23:57', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (73, 1, 0, 'DTConsole', 'Full GC Avg Time', '[{\"expr\":\"jvm_gc_collection_seconds_sum{gc=\\\"G1OldGeneration\\\",product_name=\\\"DTConsole\\\",service_name=\\\"Console\\\"}/jvm_gc_collection_seconds_count{gc=\\\"G1OldGeneration\\\",product_name=\\\"DTConsole\\\",service_name=\\\"Console\\\"}\",\"legend_format\":\"FullGCAvgTime-{{instance}}\"}]', '', 0, '2021-04-07 10:25:18', '2021-04-07 10:25:18', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (74, 1, 0, 'DTConsole', 'Full GC Count(Total)', '[{\"expr\":\"jvm_gc_collection_seconds_count{gc=\\\"G1 Old Generation\\\",product_name=\\\"DTConsole\\\",service_name=\\\"Console\\\"}\",\"legend_format\":\"FullGCCount-{{instance}}\"}]', '', 0, '2021-04-07 10:26:20', '2021-04-07 10:26:20', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (75, 1, 0, 'DTAiworks', 'Datascience_up', '[{\"expr\":\"up{product_name=\\\"DTAiworks\\\",service_name=\\\"Datascience\\\"}\",\"legend_format\":\"{{instance}}\"}]', '', 0, '2021-04-07 10:18:26', '2021-04-07 10:18:26', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (76, 1, 0, 'DTAiworks', 'Old Gen Used(%)', '[{\"expr\":\"100*jvm_memory_pool_bytes_used{pool=\\\"G1 Old Gen\\\",product_name=\\\"DTAiworks\\\",service_name=\\\"Datascience\\\"}/jvm_memory_pool_bytes_committed{pool=\\\"G1 Old Gen\\\",product_name=\\\"DTAiworks\\\",service_name=\\\"Datascience\\\"}\",\"legend_format\":\"OldGenUsed-{{instance}}\"}]', '%', 2, '2021-04-07 10:19:27', '2021-04-07 10:19:27', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (77, 1, 0, 'DTAiworks ', 'Heap Used(%)', '[{\"expr\":\"100*jvm_memory_bytes_used{area=\\\"heap\\\",product_name=\\\"DTAiworks\\\",service_name=\\\"Datascience\\\"}/jvm_memory_bytes_committed{area=\\\"heap\\\",product_name=\\\"DTAiworks\\\",service_name=\\\"Datascience\\\"}\",\"legend_format\":\"HeapUsed-{{instance}}\"}]', '%', 2, '2021-04-07 10:21:55', '2021-04-07 10:21:55', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (78, 1, 0, 'DTAiworks', 'Full GC Count(2 minutes)', '[{\"expr\":\"floor(delta(jvm_gc_collection_seconds_count{gc=\\\"G1 Old Generation\\\",product_name=\\\"DTAiworks\\\",service_name=\\\"Datascience\\\"}[2m]))\",\"legend_format\":\"FullGCCount-{{instance}}\"}]', '', 0, '2021-04-07 10:23:57', '2021-04-07 10:23:57', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (79, 1, 0, 'DTAiworks', 'Full GC Avg Time', '[{\"expr\":\"jvm_gc_collection_seconds_sum{gc=\\\"G1OldGeneration\\\",product_name=\\\"DTAiworks\\\",service_name=\\\"Datascience\\\"}/jvm_gc_collection_seconds_count{gc=\\\"G1OldGeneration\\\",product_name=\\\"DTAiworks\\\",service_name=\\\"Datascience\\\"}\",\"legend_format\":\"FullGCAvgTime-{{instance}}\"}]', '', 0, '2021-04-07 10:25:18', '2021-04-07 10:25:18', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (80, 1, 0, 'DTAiworks', 'Full GC Count(Total)', '[{\"expr\":\"jvm_gc_collection_seconds_count{gc=\\\"G1 Old Generation\\\",product_name=\\\"DTAiworks\\\",service_name=\\\"Datascience\\\"}\",\"legend_format\":\"FullGCCount-{{instance}}\"}]', '', 0, '2021-04-07 10:26:20', '2021-04-07 10:26:20', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (81, 1, 0, 'DTCommon', 'Engine_up', '[{\"expr\":\"up{product_name=\\\"DTCommon\\\",service_name=\\\"Engine\\\"}\",\"legend_format\":\"{{instance}}\"}]', '', 0, '2021-04-07 10:18:26', '2021-04-07 10:18:26', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (82, 1, 0, 'DTCommon', 'Old Gen Used(%)', '[{\"expr\":\"100*jvm_memory_pool_bytes_used{pool=\\\"G1 Old Gen\\\",product_name=\\\"DTCommon\\\",service_name=\\\"Engine\\\"}/jvm_memory_pool_bytes_committed{pool=\\\"G1 Old Gen\\\",product_name=\\\"DTCommon\\\",service_name=\\\"Engine\\\"}\",\"legend_format\":\"OldGenUsed-{{instance}}\"}]', '%', 2, '2021-04-07 10:19:27', '2021-04-07 10:19:27', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (83, 1, 0, 'DTCommon ', 'Heap Used(%)', '[{\"expr\":\"100*jvm_memory_bytes_used{area=\\\"heap\\\",product_name=\\\"DTCommon\\\",service_name=\\\"Engine\\\"}/jvm_memory_bytes_committed{area=\\\"heap\\\",product_name=\\\"DTCommon\\\",service_name=\\\"Engine\\\"}\",\"legend_format\":\"HeapUsed-{{instance}}\"}]', '%', 2, '2021-04-07 10:21:55', '2021-04-07 10:21:55', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (84, 1, 0, 'DTCommon', 'Full GC Count(2 minutes)', '[{\"expr\":\"floor(delta(jvm_gc_collection_seconds_count{gc=\\\"G1 Old Generation\\\",product_name=\\\"DTCommon\\\",service_name=\\\"Engine\\\"}[2m]))\",\"legend_format\":\"FullGCCount-{{instance}}\"}]', '', 0, '2021-04-07 10:23:57', '2021-04-07 10:23:57', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (85, 1, 0, 'DTCommon', 'Full GC Avg Time', '[{\"expr\":\"jvm_gc_collection_seconds_sum{gc=\\\"G1OldGeneration\\\",product_name=\\\"DTCommon\\\",service_name=\\\"Engine\\\"}/jvm_gc_collection_seconds_count{gc=\\\"G1OldGeneration\\\",product_name=\\\"DTCommon\\\",service_name=\\\"Engine\\\"}\",\"legend_format\":\"FullGCAvgTime-{{instance}}\"}]', '', 0, '2021-04-07 10:25:18', '2021-04-07 10:25:18', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (86, 1, 0, 'DTCommon', 'Full GC Count(Total)', '[{\"expr\":\"jvm_gc_collection_seconds_count{gc=\\\"G1 Old Generation\\\",product_name=\\\"DTCommon\\\",service_name=\\\"Engine\\\"}\",\"legend_format\":\"FullGCCount-{{instance}}\"}]', '', 0, '2021-04-07 10:26:20', '2021-04-07 10:26:20', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (87, 1, 0, 'DTTag', 'Tag_up', '[{\"expr\":\"up{product_name=\\\"DTTag\\\",service_name=\\\"Tag\\\"}\",\"legend_format\":\"{{instance}}\"}]', '', 0, '2021-04-07 10:18:26', '2021-04-07 10:18:26', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (88, 1, 0, 'DTTag', 'Old Gen Used(%)', '[{\"expr\":\"100*jvm_memory_pool_bytes_used{pool=\\\"G1 Old Gen\\\",product_name=\\\"DTTag\\\",service_name=\\\"Tag\\\"}/jvm_memory_pool_bytes_committed{pool=\\\"G1 Old Gen\\\",product_name=\\\"DTTag\\\",service_name=\\\"Tag\\\"}\",\"legend_format\":\"OldGenUsed-{{instance}}\"}]', '%', 2, '2021-04-07 10:19:27', '2021-04-07 10:19:27', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (89, 1, 0, 'DTTag ', 'Heap Used(%)', '[{\"expr\":\"100*jvm_memory_bytes_used{area=\\\"heap\\\",product_name=\\\"DTTag\\\",service_name=\\\"Tag\\\"}/jvm_memory_bytes_committed{area=\\\"heap\\\",product_name=\\\"DTTag\\\",service_name=\\\"Tag\\\"}\",\"legend_format\":\"HeapUsed-{{instance}}\"}]', '%', 2, '2021-04-07 10:21:55', '2021-04-07 10:21:55', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (90, 1, 0, 'DTTag', 'Full GC Count(2 minutes)', '[{\"expr\":\"floor(delta(jvm_gc_collection_seconds_count{gc=\\\"G1 Old Generation\\\",product_name=\\\"DTTag\\\",service_name=\\\"Tag\\\"}[2m]))\",\"legend_format\":\"FullGCCount-{{instance}}\"}]', '', 0, '2021-04-07 10:23:57', '2021-04-07 10:23:57', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (91, 1, 0, 'DTTag', 'Full GC Avg Time', '[{\"expr\":\"jvm_gc_collection_seconds_sum{gc=\\\"G1OldGeneration\\\",product_name=\\\"DTTag\\\",service_name=\\\"Tag\\\"}/jvm_gc_collection_seconds_count{gc=\\\"G1OldGeneration\\\",product_name=\\\"DTTag\\\",service_name=\\\"Tag\\\"}\",\"legend_format\":\"FullGCAvgTime-{{instance}}\"}]', '', 0, '2021-04-07 10:25:18', '2021-04-07 10:25:18', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (92, 1, 0, 'DTTag', 'Full GC Count(Total)', '[{\"expr\":\"jvm_gc_collection_seconds_count{gc=\\\"G1 Old Generation\\\",product_name=\\\"DTTag\\\",service_name=\\\"Tag\\\"}\",\"legend_format\":\"FullGCCount-{{instance}}\"}]', '', 0, '2021-04-07 10:26:20', '2021-04-07 10:26:20', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (93, 1, 0, 'DTValid', 'Valid_up', '[{\"expr\":\"up{product_name=\\\"DTValid\\\",service_name=\\\"Valid\\\"}\",\"legend_format\":\"{{instance}}\"}]', '', 0, '2021-04-07 10:18:26', '2021-04-07 10:18:26', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (94, 1, 0, 'DTValid', 'Old Gen Used(%)', '[{\"expr\":\"100*jvm_memory_pool_bytes_used{pool=\\\"G1 Old Gen\\\",product_name=\\\"DTValid\\\",service_name=\\\"Valid\\\"}/jvm_memory_pool_bytes_committed{pool=\\\"G1 Old Gen\\\",product_name=\\\"DTValid\\\",service_name=\\\"Valid\\\"}\",\"legend_format\":\"OldGenUsed-{{instance}}\"}]', '%', 2, '2021-04-07 10:19:27', '2021-04-07 10:19:27', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (95, 1, 0, 'DTValid ', 'Heap Used(%)', '[{\"expr\":\"100*jvm_memory_bytes_used{area=\\\"heap\\\",product_name=\\\"DTValid\\\",service_name=\\\"Valid\\\"}/jvm_memory_bytes_committed{area=\\\"heap\\\",product_name=\\\"DTValid\\\",service_name=\\\"Valid\\\"}\",\"legend_format\":\"HeapUsed-{{instance}}\"}]', '%', 2, '2021-04-07 10:21:55', '2021-04-07 10:21:55', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (96, 1, 0, 'DTValid', 'Full GC Count(2 minutes)', '[{\"expr\":\"floor(delta(jvm_gc_collection_seconds_count{gc=\\\"G1 Old Generation\\\",product_name=\\\"DTValid\\\",service_name=\\\"Valid\\\"}[2m]))\",\"legend_format\":\"FullGCCount-{{instance}}\"}]', '', 0, '2021-04-07 10:23:57', '2021-04-07 10:23:57', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (97, 1, 0, 'DTValid', 'Full GC Avg Time', '[{\"expr\":\"jvm_gc_collection_seconds_sum{gc=\\\"G1OldGeneration\\\",product_name=\\\"DTValid\\\",service_name=\\\"Valid\\\"}/jvm_gc_collection_seconds_count{gc=\\\"G1OldGeneration\\\",product_name=\\\"DTValid\\\",service_name=\\\"Valid\\\"}\",\"legend_format\":\"FullGCAvgTime-{{instance}}\"}]', '', 0, '2021-04-07 10:25:18', '2021-04-07 10:25:18', 1);
INSERT INTO `inspect_report_template`(`id`, `cluster_id`, `type`, `module`, `metric`, `targets`, `unit`, `decimal`, `create_time`, `update_time`, `is_deleted`) VALUES (98, 1, 0, 'DTValid', 'Full GC Count(Total)', '[{\"expr\":\"jvm_gc_collection_seconds_count{gc=\\\"G1 Old Generation\\\",product_name=\\\"DTValid\\\",service_name=\\\"Valid\\\"}\",\"legend_format\":\"FullGCCount-{{instance}}\"}]', '', 0, '2021-04-07 10:26:20', '2021-04-07 10:26:20', 1);
