apiVersion: v1
kind: PersistentVolume
metadata:
  name: empvlocal-emdb
  labels:
    localpv: emdb
spec:
  capacity:
    storage: {{.DTDBStorage}}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: emlocal-storage
  local:
    path: {{.StoragePath}}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: {{.NodeSelectKey}}
          operator: In
          values:
          - {{.NodeSelectValue}}
