apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: empvc-emdb
  namespace: {{.NameSpace}}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{.DTDBStorage}}
  storageClassName: emlocal-storage
  selector:
    matchLabels:
      localpv: emdb
