apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dt-alert
  name: dt-alert
  namespace: {{.NameSpace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dt-alert
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dt-alert
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
      - image: {{.Registory}}/{{.EmDtalertImage}}
        imagePullPolicy: IfNotPresent
        name: dt-alert
        ports:
        - containerPort: 8085
          name: server
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
