apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loki-grafana
  name: loki-grafana
  namespace: {{.NameSpace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki-grafana
  template:
    metadata:
      labels:
        app: loki-grafana
    spec:
      containers:
        - image: {{.Registory}}/{{.EmLokiGrafanaImage}}
          imagePullPolicy: Always
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: grafana-secret
            - name: GF_PATHS_PLUGINS
              value: /home/grafana/plugins
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          name: loki-grafana
          ports:
            - containerPort: 80
              name: service
              protocol: TCP
            - containerPort: 3000
              name: grafana
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: lokidata
              subPath: lokigrafanadata
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      volumes:
        - name: lokidata
          persistentVolumeClaim:
            claimName: empvc-emdb
