apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loki
  name: loki
  namespace: {{.NameSpace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - args:
            - "-config.file=/etc/loki/loki-config.yaml"
          image: {{.Registory}}/{{.EmLokiImage}}
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: http-metrics
              scheme: HTTP
            initialDelaySeconds: 45
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: loki
          ports:
            - containerPort: 3100
              name: http-metrics
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: http-metrics
              scheme: HTTP
            initialDelaySeconds: 45
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /etc/loki
              name: config-volume
            - mountPath: /loki
              name: storage
              subPath: lokidata
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: empvc-emdb
        - name: config-volume
          configMap:
            name: lokiconf
